/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
//lanjut youtube KBM Kamis,15 Juli 2021(1:48:04)
import Connection.Myconnection;
import Data.DataMahasiswa;
import Model.MahasiswaMod;
import java.awt.Color;
import java.awt.TextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class MahasiswaFrame extends javax.swing.JFrame {
    DefaultTableModel model;
    private Connection connection = null;
    MahasiswaMod mhs;
    DataMahasiswa data = new DataMahasiswa();

    
    public MahasiswaFrame() {
        initComponents();
        String [] tableAwal = {"Kode Surat","Lampiran","Tanggal Surat","Jenis Surat","Perihal","Penanggung Jawab","Jabatan"};
        model = new DefaultTableModel (tableAwal, 0);
        mhsTable.setModel(model);
        this.connection = new Myconnection().getConnection();
        tampilkanData();
        lebarJudulKolom();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanelBackgroundColor = new javax.swing.JPanel();
        lampiranText = new javax.swing.JTextField();
        kodesuratText = new javax.swing.JTextField();
        tanggalsuratText = new javax.swing.JTextField();
        jenissuratText = new javax.swing.JTextField();
        perihalText = new javax.swing.JTextField();
        penanggungjawabText = new javax.swing.JTextField();
        jabatanText = new javax.swing.JComboBox();
        simpan = new javax.swing.JButton();
        ganti = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mhsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SURAT LK APP\n");

        leftPanelBackgroundColor.setBackground(new java.awt.Color(54, 33, 89));

        lampiranText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lampiranText.setForeground(new java.awt.Color(153, 153, 153));
        lampiranText.setText("Lampiran");
        lampiranText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lampiranTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lampiranTextFocusLost(evt);
            }
        });

        kodesuratText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kodesuratText.setForeground(new java.awt.Color(153, 153, 153));
        kodesuratText.setText("Kode Surat");
        kodesuratText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        kodesuratText.setName("Kode Surat"); // NOI18N
        kodesuratText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kodesuratTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kodesuratTextFocusLost(evt);
            }
        });
        kodesuratText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kodesuratTextKeyTyped(evt);
            }
        });

        tanggalsuratText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tanggalsuratText.setForeground(new java.awt.Color(153, 153, 153));
        tanggalsuratText.setText("Tanggal Surat");
        tanggalsuratText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tanggalsuratTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tanggalsuratTextFocusLost(evt);
            }
        });

        jenissuratText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jenissuratText.setForeground(new java.awt.Color(153, 153, 153));
        jenissuratText.setText("Jenis Surat");
        jenissuratText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jenissuratTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jenissuratTextFocusLost(evt);
            }
        });

        perihalText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perihalText.setForeground(new java.awt.Color(153, 153, 153));
        perihalText.setText("Perihal");
        perihalText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                perihalTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                perihalTextFocusLost(evt);
            }
        });

        penanggungjawabText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        penanggungjawabText.setForeground(new java.awt.Color(153, 153, 153));
        penanggungjawabText.setText("Penanggung Jawab");
        penanggungjawabText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                penanggungjawabTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                penanggungjawabTextFocusLost(evt);
            }
        });

        jabatanText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jabatanText.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ketua", "Wakil Ketua", "Sekretaris", "Bendahara", "Badan Sumber Daya Manusia", "Bidang Penalaran Dan Keilmuan", "Bidang Bakat Dan Minat", "Bidang Pengabdian Masyarakat", "Bidang Komunikasi Dan Informasi", "Dosen", "Asisten Dosen", "Mahasiswa" }));
        jabatanText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanTextActionPerformed(evt);
            }
        });

        simpan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        ganti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ganti.setText("GANTI");
        ganti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gantiActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        tambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Surat LK");

        javax.swing.GroupLayout leftPanelBackgroundColorLayout = new javax.swing.GroupLayout(leftPanelBackgroundColor);
        leftPanelBackgroundColor.setLayout(leftPanelBackgroundColorLayout);
        leftPanelBackgroundColorLayout.setHorizontalGroup(
            leftPanelBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelBackgroundColorLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(leftPanelBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jabatanText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penanggungjawabText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perihalText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenissuratText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalsuratText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodesuratText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lampiranText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(leftPanelBackgroundColorLayout.createSequentialGroup()
                .addGroup(leftPanelBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelBackgroundColorLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(leftPanelBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ganti, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(leftPanelBackgroundColorLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelBackgroundColorLayout.setVerticalGroup(
            leftPanelBackgroundColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelBackgroundColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodesuratText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lampiranText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tanggalsuratText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jenissuratText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(perihalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(penanggungjawabText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jabatanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(simpan)
                .addGap(18, 18, 18)
                .addComponent(ganti)
                .addGap(18, 18, 18)
                .addComponent(hapus)
                .addGap(18, 18, 18)
                .addComponent(tambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        mhsTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mhsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Surat", "Lampiran", "Tanggal Surat", "Jenis Surat", "Perihal", "Penanggung Jawab", "Jabatan"
            }
        ));
        mhsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mhsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mhsTable);

        jPanel2.setBackground(new java.awt.Color(122, 72, 221));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1124, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logo.jpg"))); // NOI18N
        jLabel2.setText("      ");

        searchText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchText.setForeground(new java.awt.Color(153, 153, 153));
        searchText.setText("Search");
        searchText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchText.setName("Kode Surat"); // NOI18N
        searchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFocusLost(evt);
            }
        });
        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTextKeyTyped(evt);
            }
        });

        cariButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cariButton.setText("CARI");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariButton))
                .addGap(1974, 1974, 1974))
        );

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1382, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanelBackgroundColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftPanelBackgroundColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Button Simpan
    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        mhs = new MahasiswaMod();
        mhs.setKodeSurat(kodesuratText.getText());
        mhs.setLampiran(lampiranText.getText());
        mhs.setTanggalSurat(tanggalsuratText.getText());
        mhs.setJenisSurat(jenissuratText.getText());
        mhs.setPerihal(perihalText.getText());
        mhs.setPenanggungJawab(penanggungjawabText.getText());
        mhs.setJabatan((String)jabatanText.getSelectedItem());
        if(data.insertMahasiswa(mhs)){
            JOptionPane.showMessageDialog(this, "Sukses Menambah Data");
            tampilkanData();
            reset();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Menambah Data");
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void jabatanTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanTextActionPerformed
        //Under Contruction
    }//GEN-LAST:event_jabatanTextActionPerformed
    //Button Ganti
    private void gantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gantiActionPerformed
        mhs = new MahasiswaMod();
        mhs.setKodeSurat(kodesuratText.getText());
        mhs.setLampiran(lampiranText.getText());
        mhs.setTanggalSurat(tanggalsuratText.getText());
        mhs.setJenisSurat(jenissuratText.getText());
        mhs.setPerihal(perihalText.getText());
        mhs.setPenanggungJawab(penanggungjawabText.getText());
        mhs.setJabatan((String)jabatanText.getSelectedItem());
        if(data.updateMahasiswa(mhs)){
            JOptionPane.showMessageDialog(this, "Sukses Ganti Data");
            tampilkanData();
            reset();            
        } else {
            JOptionPane.showMessageDialog(this, "Gagal Ganti Data");
        }
    }//GEN-LAST:event_gantiActionPerformed
    //Menampilkan isi data tabel ke textfield
    private void mhsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mhsTableMouseClicked
       int row = mhsTable.getSelectedRow();
       
       kodesuratText.setText(mhsTable.getValueAt(row, 0).toString());
       kodesuratText.setForeground(new Color(0,0,0));
       lampiranText.setText(mhsTable.getValueAt(row, 1).toString());
       lampiranText.setForeground(new Color(0,0,0));
       tanggalsuratText.setText(mhsTable.getValueAt(row, 2).toString());
       tanggalsuratText.setForeground(new Color(0,0,0));
       jenissuratText.setText(mhsTable.getValueAt(row, 3).toString());
       jenissuratText.setForeground(new Color(0,0,0));
       perihalText.setText(mhsTable.getValueAt(row, 4).toString());
       perihalText.setForeground(new Color(0,0,0));
       penanggungjawabText.setText(mhsTable.getValueAt(row, 5).toString());
       penanggungjawabText.setForeground(new Color(0,0,0));
       jabatanText.setSelectedItem(mhsTable.getValueAt(row, 6).toString());
       kodesuratText.setEditable(false);
       
    }//GEN-LAST:event_mhsTableMouseClicked
    //Button Hapus
    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menghapus data ini?","Delete Mahasiswa",0)==0){
            mhs = new MahasiswaMod();
            mhs.setKodeSurat(kodesuratText.getText());
            if(data.deleteMahasiswa(mhs)){
                JOptionPane.showMessageDialog(this, "Sukses Menghapus Data");
                tampilkanData();
                reset();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus Data");
            }
        }
    }//GEN-LAST:event_hapusActionPerformed
    //Button  Tambah
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        tampilkanData();
        reset();
    }//GEN-LAST:event_tambahActionPerformed
    
    private void kodesuratTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodesuratTextKeyTyped
       if("".equals(kodesuratText.getText())){
        //Under Construction
        }
    }//GEN-LAST:event_kodesuratTextKeyTyped
    //Kode Surat PlaceHolder
    private void kodesuratTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kodesuratTextFocusGained
        if(kodesuratText.getText().equals("Kode Surat")){
            kodesuratText.setText("");
            kodesuratText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_kodesuratTextFocusGained
    
    private void kodesuratTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kodesuratTextFocusLost
        if(kodesuratText.getText().equals("")){
            kodesuratText.setText("Kode Surat");
            kodesuratText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_kodesuratTextFocusLost
    //Lampiran PlaceHolder
    private void lampiranTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lampiranTextFocusGained
        if(lampiranText.getText().equals("Lampiran")){
            lampiranText.setText("");
            lampiranText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_lampiranTextFocusGained

    private void lampiranTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lampiranTextFocusLost
        if(lampiranText.getText().equals("")){
            lampiranText.setText("Lampiran");
            lampiranText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_lampiranTextFocusLost
    //Tanggal Surat PlaceHolder
    private void tanggalsuratTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tanggalsuratTextFocusGained
        if(tanggalsuratText.getText().equals("Tanggal Surat")){
            tanggalsuratText.setText("");
            tanggalsuratText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_tanggalsuratTextFocusGained

    private void tanggalsuratTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tanggalsuratTextFocusLost
        if(tanggalsuratText.getText().equals("")){
            tanggalsuratText.setText("Tanggal Surat");
            tanggalsuratText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_tanggalsuratTextFocusLost
    //Jenis Surat PlaceHolder
    private void jenissuratTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jenissuratTextFocusGained
        if(jenissuratText.getText().equals("Jenis Surat")){
            jenissuratText.setText("");
            jenissuratText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jenissuratTextFocusGained

    private void jenissuratTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jenissuratTextFocusLost
        if(jenissuratText.getText().equals("")){
            jenissuratText.setText("Jenis Surat");
            jenissuratText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jenissuratTextFocusLost
    //Perihal PlaceHolder
    private void perihalTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perihalTextFocusGained
         if(perihalText.getText().equals("Perihal")){
            perihalText.setText("");
            perihalText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_perihalTextFocusGained

    private void perihalTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perihalTextFocusLost
        if(perihalText.getText().equals("")){
            perihalText.setText("Perihal");
            perihalText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_perihalTextFocusLost
    //Penanggung Jawb PlaceHolder
    private void penanggungjawabTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_penanggungjawabTextFocusGained
        if(penanggungjawabText.getText().equals("Penanggung Jawab")){
            penanggungjawabText.setText("");
            penanggungjawabText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_penanggungjawabTextFocusGained

    private void penanggungjawabTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_penanggungjawabTextFocusLost
        if(penanggungjawabText.getText().equals("")){
            penanggungjawabText.setText("Penanggung Jawab");
            penanggungjawabText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_penanggungjawabTextFocusLost
    //Search PlaceHOlder
    private void searchTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusGained
        if(searchText.getText().equals("Search")){
            searchText.setText("");
            searchText.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_searchTextFocusGained

    private void searchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusLost
        if(searchText.getText().equals("")){
            searchText.setText("Search");
            searchText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_searchTextFocusLost

    private void searchTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyTyped
        //Coming Soon
        System.out.println("Search Text Field Under Construction!");
        JOptionPane.showMessageDialog(this, "Coming Soon!!!");
    }//GEN-LAST:event_searchTextKeyTyped

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        String cariDataTabel = searchText.getText();
        
    }//GEN-LAST:event_searchTextKeyReleased

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        
    }//GEN-LAST:event_cariButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MahasiswaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariButton;
    private javax.swing.JButton ganti;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jabatanText;
    private javax.swing.JTextField jenissuratText;
    private javax.swing.JTextField kodesuratText;
    private javax.swing.JTextField lampiranText;
    private javax.swing.JPanel leftPanelBackgroundColor;
    private javax.swing.JTable mhsTable;
    private javax.swing.JTextField penanggungjawabText;
    private javax.swing.JTextField perihalText;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tanggalsuratText;
    // End of variables declaration//GEN-END:variables

    private void tampilkanData() {
        List<MahasiswaMod> ls = new ArrayList<MahasiswaMod>();
        
        ls = new DataMahasiswa().getAll();
        String Data[][] = new String[ls.size()][7];
        for(int i = 0; i < ls.size(); i++){
            Data[i][0] = ls.get(i).getKodeSurat();
            Data[i][1] = ls.get(i).getLampiran();
            Data[i][2] = ls.get(i).getTanggalSurat();
            Data[i][3] = ls.get(i).getJenisSurat();
            Data[i][4] = ls.get(i).getPerihal();
            Data[i][5] = ls.get(i).getPenanggungJawab();
            Data[i][6] = ls.get(i).getJabatan();
        }
        mhsTable.setModel(new DefaultTableModel(Data, new String[]{"kodeSurat","lampiran","tanggalSurat","jenisSurat","perihal","penanggungJawab","jabatan"}));
    }

    private void reset() {
        kodesuratText.setText("");
        lampiranText.setText("");
        tanggalsuratText.setText("");
        jenissuratText.setText("");
        perihalText.setText("");
        penanggungjawabText.setText("");
        jabatanText.setSelectedItem("Ketua");
        kodesuratText.setEditable(true);
    }

    private void lebarJudulKolom() {
        TableColumn column;
        mhsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        //Kolom Kode Surat
        column = mhsTable.getColumnModel().getColumn(0); 
        column.setPreferredWidth(115);
        //Kolom Lampiran
        column = mhsTable.getColumnModel().getColumn(1); 
        column.setPreferredWidth(60); 
        //Kolom Tanggal Surat
        column = mhsTable.getColumnModel().getColumn(2); 
        column.setPreferredWidth(125); 
        //Kolom Jenis Surat
        column = mhsTable.getColumnModel().getColumn(3); 
        column.setPreferredWidth(150); 
        //Kolom Perihal
        column = mhsTable.getColumnModel().getColumn(4); 
        column.setPreferredWidth(125); 
        //Kolom Penanggung Jawab
        column = mhsTable.getColumnModel().getColumn(5); 
        column.setPreferredWidth(150); 
        //Kolom Jabatan
        column = mhsTable.getColumnModel().getColumn(6); 
        column.setPreferredWidth(288); 
    }

   
}
